[metadata]
addr = 4506
size = 1016
last_change = 1671034235

[stack_vars.-1c]
last_change = 1671022466
stack_offset = -28
stack_offset_type = 1
name = "v20"
type = "unsigned int"
size = 4
addr = 4506

[stack_vars.-38]
last_change = 1671033947
stack_offset = -56
stack_offset_type = 1
name = "func"
type = "long *"
size = 8
addr = 4506

[stack_vars.-120]
last_change = 1671034080
stack_offset = -288
stack_offset_type = 1
name = "arr"
type = "short[6]"
size = 12
addr = 4506

[stack_vars.-108]
last_change = 1671034235
stack_offset = -264
stack_offset_type = 1
name = "data_arr"
type = "long[24]"
size = 192
addr = 4506
