[metadata]
addr = 4506
size = 1016
last_change = 1671022466

[stack_vars.-1c]
last_change = 1671022466
stack_offset = -28
stack_offset_type = 1
name = "v20"
type = "unsigned int"
size = 4
addr = 4506
